export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const RESTORE_INGREDIENTS = 'RESTORE_INGREDIENTS';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const ADD_ORDER_START = 'ADD_ORDER_START';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED';

export const CANCEL_ORDER_START = 'CANCEL_ORDER_START';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAILED = 'CANCEL_ORDER_FAILED';

export const INIT_ORDER = 'INIT_ORDER';
export const LOAD_ORDERS = 'LOAD_ORDERS';
export const SEND_ORDER = 'SEND_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const SET_ORDER_SEARCH_DATE = 'SET_ORDER_SEARCH_DATE';
export const SET_ORDER_SORTING = 'SET_ORDER_SORTING';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH';
export const AUTH_RESTORE_TOKENS = 'AUTH_RESTORE_TOKENS';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

export const PERFORM_STEP_NEXT = 'PERFORM_STEP_NEXT';
export const PERFORM_STEP_BACK = 'PERFORM_STEP_BACK';
export const PERFORM_STEP_RESET = 'PERFORM_STEP_RESET';
export const HIDE_BURGER_STEPPER = 'HIDE_BURGER_STEPPER';
export const DISPLAY_BURGER_STEPPER = 'DISPLAY_BURGER_STEPPER';

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const RESTORE_CURRENCY = 'RESTORE_CURRENCY';

export const CHANGE_THEME = 'CHANGE_THEME';
export const RESTORE_THEME = 'RESTORE_THEME';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const RESTORE_LANGUAGE = 'RESTORE_LANGUAGE';

export const CHANGE_PROFILE_IMAGE = 'CHANGE_PROFILE_IMAGE';
export const RESTORE_PROFILE_IMAGE = 'RESTORE_PROFILE_IMAGE';
export const REMOVE_PROFILE_IMAGE = 'REMOVE_PROFILE_IMAGE';

export const ADD_SETTINGS_START = 'ADD_SETTINGS_START';
export const ADD_SETTINGS_SUCCESS = 'ADD_SETTINGS_SUCCESS';
export const ADD_SETTINGS_FAILED = 'ADD_SETTINGS_FAILED';
export const SEND_SETTINGS = 'SEND_SETTINGS';
export const ADD_SETTINGS_LOCALLY = 'ADD_SETTINGS_LOCALLY';

export const FETCH_SETTINGS_START = 'FETCH_SETTINGS_START';
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_FAILED = 'FETCH_SETTINGS_FAILED';
export const LOAD_SETTINGS= 'LOAD_SETTINGS';

export const CHANGE_BURGER_TYPE = 'CHANGE_BURGER_TYPE';
export const RESTORE_BURGER_TYPE = 'RESTORE_BURGER_TYPE';

export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const DELETE_ACCOUNT_START = 'DELETE_ACCOUNT_START';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
